// apps/react/src/features/anime/components/AnimeDetails/AnimeDetails.tsx
import { formatDate } from '@js-camp/core/utils/formatDate';
import {
  selectGenreListIds,
  selectStudioListId,
} from '@js-camp/react/store/animeExtender/selectors';
import { useAppSelector } from '@js-camp/react/store/store';
import { Grid } from '@mui/material';
import { memo, FC } from 'react';

import { selectGenreList } from '@js-camp/react/store/genre/selectors';
import { selectStudioList } from '@js-camp/react/store/studio/selectors';

import { AnimeFull } from '@js-camp/core/models/animeFull';

import styles from './AnimeDetails.module.css';

interface Props {

  /** Anime. */
  readonly anime: AnimeFull;
}

/** Anime details description page component. */
const AnimeDetailsPageComponent: FC<Props> = ({ anime }) => {

  const studioListIds =
    useAppSelector(state => selectStudioListId(state, anime.id)) ?? [];
  const genreListIds =
    useAppSelector(state => selectGenreListIds(state, anime.id)) ?? [];
  const studioList = useAppSelector(state =>
    selectStudioList(state, [...studioListIds]));
  const genreList = useAppSelector(state =>
    selectGenreList(state, [...genreListIds]));

  return (
    <Grid spacing={2} container>
      <Grid item xs={3}>
        <img
          className={styles['anime__image']}
          alt={`image of anime ${
                anime.titleEnglish || anime.titleJapanese
          }`}
          src={anime.image}
        />
      </Grid>

      <Grid item xs={9}>
        <Grid className={styles['anime__detail']}>
          <p className={styles['anime__title-english']}>
            {anime.titleEnglish}
          </p>
          <p className={styles['anime__title-japanese']}>
            {anime.titleJapanese}
          </p>
        </Grid>
        <Grid className={styles['anime__detail']}>
          <span className={styles['anime__title-details']}>Aired</span>
          <span>
            {formatDate(anime.airingStart)} to{' '}
            {formatDate(anime.airingFinish)}
          </span>
        </Grid>
        <Grid className={styles['anime__detail']}>
          <span className={styles['anime__title-details']}>Type</span>
          <span>{anime.type}</span>
        </Grid>
        <Grid className={styles['anime__detail']}>
          <span className={styles['anime__title-details']}>Status</span>
          <span>{anime.status}</span>
        </Grid>
        <Grid className={styles['anime__detail']}>
          {studioList.length > 0 ? (
            <>
              <span className={styles['anime__title-details']}>
                    Studios
              </span>
              <span>
                {studioList.map(studio => studio.name).join(', ')}
              </span>
            </>
          ) : (
            <></>
          )}
        </Grid>
        <Grid className={styles['anime__detail']}>
          {genreList.length > 0 ? (
            <>
              <span className={styles['anime__title-details']}>Genres</span>
              <span>{genreList.map(genre => genre.name).join(', ')}</span>
            </>
          ) : (
            <></>
          )}
        </Grid>
      </Grid>
      {anime.synopsis !== undefined ? (
        <Grid item xs={12} className={styles['anime__detail']}>
          <span className={styles['anime__title-details']}>Synopsis</span>
          <p>{anime.synopsis}</p>
        </Grid>
      ) : (
        <></>
      )}
    </Grid>
  );
};

export const AnimeDetailsPage = memo(AnimeDetailsPageComponent);

// apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { AnimeFull } from '@js-camp/core/models/animeFull';
import { Observable, map, switchMap } from 'rxjs';

import { Studio } from '@js-camp/core/models/studio';
import { Genre } from '@js-camp/core/models/genre';

import { ANIME_ID_ROUTE_PARAM } from '../anime.module';

import { AnimeService } from '../../../../core/services/anime/anime.service';

/** Page with information about anime. */
@Component({
  selector: 'camp-anime-details',
  templateUrl: './anime-details.component.html',
  styleUrls: ['./anime-details.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AnimeDetailsComponent {

  /** Separator. */
  public separator = ' ';

  /** Anime information. */
  public readonly anime$: Observable<AnimeFull>;

  public constructor(
    route: ActivatedRoute,
    animeService: AnimeService,
  ) {
    const animeId$ = route.paramMap.pipe(
      map(params => Number(params.get(ANIME_ID_ROUTE_PARAM))),
    );
    this.anime$ = animeId$.pipe(
      switchMap(id => animeService.fetchAnimeById(id)),
    );
  }

  /**
   * Join array studios or genres separated by spaces.
   * @param array Array studios or genres.
   */
  public joinSeparatedBySpace(array: Studio[] | Genre[]): string {
    return array.map(element => element.name).join(this.separator);
  }
}

<div class="loading-layout">
  <ng-template class="loading-layout" #loading>
    <mat-progress-bar mode="indeterminate"></mat-progress-bar>
  </ng-template>
</div>
<div class="anime" *ngIf="anime$ | async as anime; else loading">
  <img
    class="anime__image"
    [src]="anime.image"
    alt="image of anime {{ anime.titleEnglish || anime.titleJapanese }}"
  />
  <div>
    <div>
      <p class="anime__title-english">{{ anime.titleEnglish }}</p>
      <p class="anime__title-japanese">{{ anime.titleJapanese }}</p>
    </div>
    <div class="anime__detail">
      <span class="anime__title-details">Aired</span>
      <span>{{anime.airingStart | formatDate}} to {{anime.airingFinish | formatDate}}</span>
    </div>
    <div class="anime__detail">
      <span class="anime__title-details">Type</span>
      <span>{{anime.type}}</span>
    </div>
    <div class="anime__detail">
      <span class="anime__title-details">Status</span>
      <span>{{anime.status}}</span>
    </div>
    <div class="anime__detail">
      <span class="anime__title-details">Studios</span>
      <span>{{joinSeparatedBySpace(anime.studiosData)}}</span>
    </div>
    <div class="anime__detail">
      <span class="anime__title-details">Genres</span>
      <span>{{joinSeparatedBySpace(anime.genresData)}}</span>
    </div>
    <div class="anime__detail">
      <span class="anime__title-details">Synopsis</span>
      <span>{{anime.synopsis}}</span>
    </div>
  </div>
</div>
